name: Terraform Stage Pipeline

on:
  push:
    branches:
      - stage

jobs:
  terraform:
    name: Terraform Stage
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./environments/stage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve