name: Terraform stage

on:
  push:
    branches:
      - stage

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init
        working-directory: environments/stage

      - name: Terraform Plan
        run: terraform plan
        working-directory: environments/stage

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: environments/stage
     
